### ISSUE TITLE
Removing basic blocks / Removing instructions

### ISSUE THREAD

**Issue by nowraiz** [columbia/egalito#27]
I want to use egalito tool to remove some basic blocks from the binary as opposed to adding a few instructions. Is it possible to do so? I don't see any related documentation for this task.

**Comment by dwks** [comment]
Certainly. The `ChunkMutator` class has a `remove` function. You can remove individual instructions from a basic block until it is empty, or just remove a basic block from a function. Note that this does not free the Chunks -- in case there are incoming pointers from other places. But once the Chunks are removed from the hierarchy they will no longer appear in iteration or generated code.

**Comment by nowraiz** [comment]
Thanks for the response. I tried joining slack before but it does not let me join the workspace without invitation. Where can I get that?

**Comment by dwks** [comment]
Please contact us at help at egalito dot org with the email address you want to register for the slack. You can also find my personal contact info on my website.
